### ISSUE TITLE
Previous build not restored from cache, potentially causing 404s

### ISSUE THREAD

**Issue by alismith-dev** [febeling/webpack-rails-buildpack#11]
There is an edge case where a page loads at the same time as the deploy switches from old to new dynos. The page contains references (e.g. `<script>`) to out-of-date assets from the previous deploy, but the client does not have time to download them before the dynos are switched.

The new dyno then does not contain these old assets and would therefore 404. The new dyno only contains assets from the new build. This could only happen in a very short window, however it could be exaggerated by slow/flaky connections.

If the previous deploy's output assets could be pulled from cache and persisted into the new dyno, the problem would be fixed. Note that it would be sensible to restrict this to only the last deploy's output, otherwise the cache may become bloated.

Unfortunately the buildpack doesn't know where the output assets be put, and thus can't move it into the cache. The only options that I could think of to resolve this would be to assume the use of an environment variable or to somehow introspect webpack itself to find the output directory. Do you think either of these are options that you would accept a PR for?

**Comment by febeling** [comment]
That sounds like quite a lump of complexity for something that happens only during a this split-second time window. Do you have an actual application where you'd see this making sense in a measurable way, according to access logs and error patterns and all that?

I'd think most bigger deployments will notch up min cache expiry in the CDN just a tiny bit, or something like that, a be good...

**Comment by jdleesmiller** [comment]
Thanks for the quick response! I had a look at our logs, and we do get a surprising number of 404s for an old bundle, even a few days after the last time we deployed (on Thu 19 Jan).

![image](https://cloud.githubusercontent.com/assets/160829/22211255/69709e66-e184-11e6-90c1-b97bb1f62fa9.png)

(Well, it is actually a pretty small number compared to the total number of requests for the bundle, but it may have caused some pretty strange errors for anyone that it did affect.)

So, I think there are a few use cases here that would be served by keeping some old files around:

1. The one outlined in the original issue, in the first few seconds of the deploy.

2. If you use some of webpack's cleverer asynchronous code splitting techniques, then conceivably an old version of the page could after some time request an older code bundle that has since been updated. The same would I think apply if you have any asynchronously loaded assets such as images.

3. Caching... mysteries? I am still not entirely sure how clients are still making these requests days later --- it seems to require that they load an old version of the page from cache but then decide to re-request the scripts on the page.

We're not currently using a CDN for these assets --- we just use the default heroku configuration, which is to serve them from the rails app via heroku. One could certainly argue that we should be using a CDN, but I don't think everyone does.

Sprockets-rails does go out of its way to keep 'backups' of the old assets that it generates, I guess for some of the reasons above. Their logic is here: https://github.com/rails/sprockets/blob/5c2021f69c2820044ed4d29e1fab85c34306efd3/lib/sprockets/manifest.rb#L232-L262

I think if the buildpack could work out the location of the webpack files to store, which seems to be the first hurdle here, actually keeping and restoring the files should be fairly straightforward (famous last words...).

**Comment by febeling** [comment]
I'm quite sure there are valid use-cases for this feature. But I'm not convinced that this package is the right place for them. webpack-rails-buildpack is largely a thin wrapper around running `rake webpack:compile` at the right time. It invokes a build task that ships with `webpack-rails` and integrates it as part of the Heroku deployment process.

What you describe here is quite orthogonal to that. I don't want this packageto become a place to accumulate webpack-related functionality of all sorts, if only for the reason that I don't have the setup to properly test and quality assure this part.

Don't be disappointed though. Maybe I can inspire you to create your own buildpack for what you are planning. It really isn't much more than a short shell script at a well-known location.

The only complication is how the environment variables from the heroku config actually are actually files of these names in a specific directory location. Everyone expects them to be environment variables, but in order to have them as environment you need to [load these files into them](https://github.com/febeling/webpack-rails-buildpack/blob/master/bin/compile#L19). Many buildpacks do exactly that, as does this. But other than that, it's a short shell script.

So maybe you fork this repo and change everything over, or you head to heroku docs and start from scratch. But it's quite simple to put something in place here that does what you need. And once you feel it's a solution that is general enough to be of use for others you can still publish it standalone. 

On top, you might be able to serve users outside the rails corner of the webpack community.

**Comment by alismith-dev** [comment]
Ok. I understand your position 😄  We'll take it forward as a fork if necessary.

Closing
