### ISSUE TITLE
NPM and Yarn Slapfight

### ISSUE THREAD

**Issue by Petercopter** [febeling/webpack-rails-buildpack#14]
It looks like this buildpack is hardcoded to use NPM instead of Yarn. We ran into a problem where Yarn was installing and respecting it's lockfile, but then NPM was coming through and installing without a lockfile, thereby overwriting some locked versions.

For the moment we just forked and removed the NPM install line. What would be the best course of action for detecting whether to use Yarn or NPM?

**Comment by febeling** [comment]
@Petercopter—I'm not sure. Do you have an idea?

**Comment by brunoarueira** [comment]
@Petercopter @febeling I think the best bet is to make like the heroku do that! Something along those lines here https://github.com/heroku/heroku-buildpack-nodejs/blob/2403875f08747b5f7c45dbc61a1d5239959f6042/lib/failure.sh#L4 and here https://github.com/heroku/heroku-buildpack-nodejs/blob/2403875f08747b5f7c45dbc61a1d5239959f6042/bin/compile#L63. If the ```$YARN``` is exposed will be much better otherwise, just replicate the conditions.

**Comment by febeling** [comment]
@brunoarueira @Petercopter - yes, that looks reasonable. I'd accept a patch following this approach.
